services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:8080
    environment:
      - PORT=8080



# front:
#   build:
#     context: ../angular-app
#     dockerfile: deploy/Dockerfile-multi
#   ports:
#     - 80:80
#     - 443:443